spring.application.name=ShareMyRecipe
server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# driver is a tool for converting in a language mysql understand
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
# dialect is a language
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQL8Dialect}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#S3 bucket
cloud-aws-credentials-access-key=${AWS_BUCKET_ACCESS_KEY}
cloud-aws-credentials-secret-key=${AWS_BUCKET_SECRET_KEY}
cloud-aws-region-static=${AWS_BUCKET_REGION}
cloud-aws-s3-bucket=${AWS_BUCKET_NAME}

jwt-secret-key=${JWT_SECRET_KEY}

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:sharemyrecipe
#spring.datasource.username=user
#spring.datasource.password=password
management.endpoint.health.show-data=active
management.endpoint.web.exposure.include=*